version: '3.8'
services:
  django:
    build: ./backend
    container_name: djangoapp
    restart: always
    ports:
      - 8888:8000
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - myNetwork
    depends_on:
      - postgres
    env_file:
      - ./.env

  node:
    build: ./frontend
    container_name: reactapp_kanalservice
    restart: always
    ports:
      - 3333:3000
    command: npm start
    depends_on:
      - django
    networks:
      - myNetwork
  tgbot:
    build: ./tgbot
    container_name: kanalservice_bot
    restart: always
    command: python main.py

  postgres:
    # Так же разворачиваем с готового контейнера
    image: postgres:15-alpine
    container_name: postgresdb
    # Чтобы наши данные не пропадали при перезапуске подключсим volume
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    # Переменные окружения. их надо будет передавать в django.
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=django_db
    # Сеть
    networks:
      - myNetwork

volumes:
  postgres_volume:

networks:
  myNetwork:
    driver: bridge
