# Generated by Django 4.1.7 on 2023-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='номер заказа')),
                ('order_cost_in_dollars', models.IntegerField(verbose_name='стоимость заказа в долларах')),
                ('delivery_time', models.DateField(verbose_name='срок поставки')),
                ('order_cost_in_rubles', models.FloatField(verbose_name='стоимость заказа в долларах')),
            ],
        ),
    ]
